### ISSUE TITLE
EarlyGameConfig defined in EarlyGameClient, not EarlyGame

### ISSUE THREAD

**Issue by sylv256** [JayCeeCreates/earlygame#11]
# help
https://pastebin.com/1PaqfhEj

[***bruh***](https://github.com/JayCeeCreates/earlygame/blob/6a0a0034df5c5bce23cfd14f1f5dba96038fc891/src/main/java/jayceecreates/earlygame/world/StickTwigGen.java#L26)

# Description
StickTwigGen.generate reads client-side field EarlyGameClient.CONFIG on Dedicated Server

**Comment by sylv256** [comment]
lol guess i can't use it on a server

**Comment by TehcJS** [comment]
fixed
i'll go pr soon i'm tired

**Comment by sylv256** [comment]
ok pr'ing now

**Comment by sylv256** [comment]
#12 Fixes this issue

**Comment by sylv256** [comment]
Protip: Never define your game config in the client-side entrypoint. lol

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

Will keep that in mind in the future~
