### ISSUE TITLE
Add flint to pick up on ground

### ISSUE THREAD

**Issue by tyra314** [JayCeeCreates/earlygame#13]
I found plenty of sticks and stones on the ground during some testing, ready to pick up. So getting these is quite easy and also fun. Just collect them and explore further in the world. But getting flint seems like a grind* in comparison. To get flint, you need to mine gravel (or dirt) and hope for flint to drop by chance. Given the flint tools aren't durable at all, I feel like I need quite a lot of flint to progress to copper tools, which means a lot of mined gravel.

I think a good solution would be to spawn flint just like rocks and sticks on the ground to pick up on the go. Spawning might be limited to be on top of grave blocks. 

*Let's crush some numbers, shall we? To progress to copper tools, you need to craft a flint pickaxe, and you probably want to craft a flint pickaxe as well for some wood shopping. To build these two tools, you need three flint shards and two lashings. To get the lashings, you need 8 plant fibers. With a drop chance of 27.5% and 20 durability points for one flint knife, this means you need to craft on average two knives to get enough fibers. Thus, in total, you need a bare minimum of five flints. With a drop chance of 10% or 5%, this means you need to punch on average 50 gravel or 100 dirt blocks, respectively.  Given there is no shovel, that's quite a lot to punch with your fists. And that's the bare minimum. Imagine you don't immediately find a cave and need to actually mine a bunch of stone to find copper, or you may want to get a shelter. In such cases, you could run through some tools as they have quite low durability.

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

This sounds like it would clutter the ground with too much objects already. Fortunately, I came up with a solution for you to likely get more flint shards, and it will be done in the upcoming stable release.

Closing this-
