### ISSUE TITLE
Some questions and feature requests.

### ISSUE THREAD

**Issue by K0-RR** [JayCeeCreates/earlygame#14]
I tried breaking some grass but nothing. **I figured I need to use a knife but this should be in the description.**

**Comment by K0-RR** [comment]
What does  "harderGroundBlocks": true," do? I can't find this in the description.

**Comment by K0-RR** [comment]
Please add a config for disabling copper.

**Comment by JayCeeCreates** [comment]
1. There's a wiki for that.
2. harderGroundBlocks makes you destroy some ground blocks like dirt slower in order to add realism.
3. With other configs in default and copper ore generation disabled, progression is virtually impossible, y'know? But I'll do it cuz yes >:)

**Comment by JayCeeCreates** [comment]
Latest release is out! 3rd item should be implemented by now.
