### ISSUE TITLE
Rocks hitboxes are too small.

### ISSUE THREAD

**Issue by K0-RR** [JayCeeCreates/earlygame#15]
![image](https://user-images.githubusercontent.com/43277609/110645855-a065f700-81b6-11eb-9999-a8a18dd81833.png)
It's hard to click them

Here is a screenshot from a mod "This Rocks" - their hitboxes are too big (full block in width and depth)
![image](https://user-images.githubusercontent.com/43277609/110646206-f9ce2600-81b6-11eb-9240-26a3154d1e3f.png)

And maybe add a height to the sticks hitboxes

**Comment by JayCeeCreates** [comment]
The hitbox should match the model of the rock in my mod, but the large hitbox is something they prefer in their mod. I feel like it's something not really necessary to "improve" upon for EarlyGame.
