### ISSUE TITLE
make no tree punching optional

### ISSUE THREAD

**Issue by nullified33** [JayCeeCreates/earlygame#17]
i was trying to play survival with around 150 mods and being unable to break trees makes survival virtually impossible

**Comment by JayCeeCreates** [comment]
How is it virtually impossible? Can't you get flint, knap it to make flint shards, craft a flint knife, cut grass with a knife to get plant fiber, craft a lashing, then craft a flint axe to cut trees or something?

**Comment by nullified33** [comment]
> How is it virtually impossible? Can't you get flint, knap it to make flint shards, craft a flint knife, cut grass with a knife to get plant fiber, craft a lashing, then craft a flint axe to cut trees or something?

Basically one of my mods makes oak sticks spawn rather than normal sticks so you cant  craft with flint

**Comment by nullified33** [comment]
https://www.curseforge.com/minecraft/mc-mods/atbyw

**Comment by JayCeeCreates** [comment]
Okay so I tested the mod and it turns out that there are incompatibility issues. You can still use oak sticks to make flint and copper tools but it doesn't work for other stick variants.

I'll hook you up with a fix soon.

**Comment by JayCeeCreates** [comment]
Snapshot ready. This should address the compatibility issue.
https://github.com/JayCeeCreates/earlygame/releases/tag/1.16.x-1.0.2-S1

Lemme know if you have any inquiries, and I will reopen the issue.
