### ISSUE TITLE
Smithee compatability

### ISSUE THREAD

**Issue by ghost** [JayCeeCreates/earlygame#20]
e.g. can't use axes because of No Tree Punching mechanic

**Comment by JayCeeCreates** [comment]
Fixed. I also made an issue to the Smithee mod to add the base Smithee tools to the Fabric tool tag database to improve compatibility with other mods that use such mod.

You can download the .jar here. Lemme know if you have any more inquiries.
https://github.com/JayCeeCreates/earlygame/releases/tag/1.16.x-1.0.2-S2

**Comment by JayCeeCreates** [comment]
So I went back to playtest my mod and this "fix" completely broke the mod lol

Smithee has to do something about it, not really my issue. 🤔

**Comment by PaulZappia** [comment]
> Smithee has to do something about it, not really my issue. 🤔

This same issue seems to be occuring with this other mod that adds tools and weapons (mainly with axes): https://www.curseforge.com/minecraft/mc-mods/nicos-extra-items

There could still be an issue with EarlyGame but I'm not too sure since this mod's source isn't available for viewing.

**Comment by JayCeeCreates** [comment]
This is why open-sourcing mods are essential so that people can make suggestions like this...

**Comment by JayCeeCreates** [comment]
Anyways, the pull request I made on Smithee was merged, so it should be fixed. Lemme know if you have any more issues and I'll open it once again.
