### ISSUE TITLE
Sticks and rocks not generating in non-vanilla biomes

### ISSUE THREAD

**Issue by SleepyTonia** [JayCeeCreates/earlygame#22]
As the title says, the biomes from mods such as Biomes you'll go (BYG) are sometimes simply unplayable "early game" because of this issue. It's not game-breaking, but I believe that at least sticks should generate by default in modded biomes, perhaps defaulting to normal stone rocks in those cases.

**Comment by SleepyTonia** [comment]
Seems like the issue is on BYG's side

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

I can definitely see that, considering I have played a lot of this mod with Traverse and rocks cannot spawn on modded biomes. It seems to me that it wasn't possible for me to just manually add world generation on a modded biome (or at least I don't have a knowledge for it yet). I think it needs to make a dependency with something like Traverse or OTBYG but then again I can't really say anything more about this matter, soz ;;

**Comment by SleepyTonia** [comment]
No biggie~ I looked at the worldgen code for BYG and it really messes, or rather _doesn't_ interact with a lot of the regular Fabric biome modding features. I just cloned the repository and created my own custom version with your sticks re-created in most biomes. (I wanted to use your mod *that* badly 🤣)

**Comment by JayCeeCreates** [comment]
Cheers for the open source-
