### ISSUE TITLE
[Mod Compat] Minegate

### ISSUE THREAD

**Issue by MissGamerz** [JayCeeCreates/earlygame#23]
i see youve added atbw but minegate anther mod which has waaay more stuff and covers the same functionality is not compatible with your mod, however they include tags in their mod "minecraft:sticks" to give compat to other mods 

could you please add this???

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

I've looked into the code for Minegate, and it seems like it's both this and that mod's issue.
- On my hand, I have to change the tool recipes to use a common stick tag for better compatibility with other mods.
- On the other hand, Minegate (and other possible mods that add stick variants) has to make a common tag for sticks.

I'll try to get in touch with the other party.

**Comment by JayCeeCreates** [comment]
Extra note: it also seems like the other party has the code in open source, but has the license of "All Rights Reserved" 🤔

**Comment by MissGamerz** [comment]
if everyone used minecraft:sticks 

that would be nice as it would make sense

so this would be more to get atbyw to use the same thing as minegate to get this stuff compatible as using a common dir as the data pack such as minecraft will help modpacks such as ours so we can overwrite them easily due to the way fabric loads mod datapacks vs minecraft 

we use datapacks to refine stuff in our packs which has been an adventure because of fabric using datapack and overwriting vanilla behaviour so this is how im discovering all this with mods tags as the only way you can get these tags is by open the jar with a archive program and check the datapack it includes oorr github, 9/10 they dont document it its been annoying

**Comment by JayCeeCreates** [comment]
MineGate dev merged my PR regarding sticks, so I consider this issue closed-
