### ISSUE TITLE
Feature Req: Config file should include an option to disable Copper Armors and Weapons 

### ISSUE THREAD

**Issue by Feriguel** [JayCeeCreates/earlygame#24]
Config files should include an option to remove copper armor and weapons, with the exception of knives and saws.

The option would allow a user to decide which armor variant to use between this mod and other mods like Easy Emerald Tools.

https://www.curseforge.com/minecraft/mc-mods/simple-emerald-tools-fabric

**Comment by JayCeeCreates** [comment]
The thing is... this will break some .json files with copper tools included, such as `FabricToolTags.PICKAXES`. If an item or a block listed in such tags are not found, it will simply not load, and all other tools (i.e. flint pickaxe) in this mod will be affected.

**Comment by Feriguel** [comment]
I see, then I will close the feature request. Keep up the great work!
