### ISSUE TITLE
Cobblestone variants can not be mined with any pickaxe.

### ISSUE THREAD

**Issue by Feriguel** [JayCeeCreates/earlygame#25]
Andesite, Diorite and Granite cobblestone are currently mined in the same way one would punch a cobblestone in vanilla. They take a long time to break, and do not drop anything.

**Comment by JayCeeCreates** [comment]
What version of Minecraft and EarlyGame are you using?

EDIT: nvm, it's 1.17. mojank definitely changed how you mine modded blocks ;;

**Comment by JayCeeCreates** [comment]
This snapshot release should solve it. Lemme know if you have any more inquiries~
https://github.com/JayCeeCreates/earlygame/releases/tag/1.17.x-1.0.4-S1
