### ISSUE TITLE
[Bug] Lang assets (Servers)

### ISSUE THREAD

**Issue by MissGamerz** [JayCeeCreates/earlygame#26]
your language file /assests/minecraft/lang/en_us.json breaks all vanilla messages in console for servers

move your messages to your mods dedicated lang and use that for your mod specific messages and that will fix this, otherwise you will have to include all vanilla messages(which would remove customisation of those messages due to your mod overwriting them)

**Comment by JayCeeCreates** [comment]
What version of mod do you use?

**Comment by MissGamerz** [comment]
the newest (at the time)

**Comment by CloudTheWolf** [comment]
Have been able to replicate this in version 1.17.x-1.1.1

**Comment by Zekiu** [comment]
Still happens on 1.19
![image](https://user-images.githubusercontent.com/68301723/179310533-0e21f845-91fe-4270-a801-6a844de5ef1f.png)
