### ISSUE TITLE
[Mod Compat] This Rocks

### ISSUE THREAD

**Issue by MissGamerz** [JayCeeCreates/earlygame#28]
# Explaining
this rocks adds rocks stick itself plus other things, I was wondering if you and the dev of this mod could team up to make the mods compatible with each other. 
(e.g. disable your stick and rock generation when that mod is installed and replace his drops with yours or something like that)
this would make it seamless between the mods, and although your mods do similar things your ideas are very different. i dont think the mods should merge as they have different purposes but it be handy if both were installed for them to work together

# Link
https://modrinth.com/mod/this-rocks

**Comment by theDerxu** [comment]
this would be cool

**Comment by JayCeeCreates** [comment]
Gotta admit, it'd be interesting if items from This Rocks can be used as ingredients for the EarlyGame tools, but since the stick and rock generations of the two mods overlap with each other, I think it's best not to proceed further with this idea.
