### ISSUE TITLE
Industrial Revolution incompatibility

### ISSUE THREAD

**Issue by crysthala** [JayCeeCreates/earlygame#32]
**Description:** EarlyGame appears to have a compatibility issue with Industrial Revolution. EG apparently breaks Indrev's recipe system somehow while removing vanilla recipes. It takes two to tango, so I'll report on the Indrev tracker as well.

**Steps to Reproduce:**
1. Install EG and Indrev together and launch Minecraft.
2. Open or create a world and wait for the little loading square to fill up.
3. Enjoy the resulting crash to desktop.

**Technical Information:**
- Minecraft: 1.17.1, bundled Java runtime, Fabric Loader 0.11.6
- Cloth Config API: 5.0.38
- EarlyGame: 1.1.1
- Fabric API: 0.37.2
- Fabric Language Kotlin: 1.6.2
- Industrial Revolution: 1.10.0-alpha.12
- Modpack: N/A. I build my own. Tinkering is half the fun!

**Logs:** Here's a crash log in a "clean room" profile, with only EG, Indrev, and their dependencies installed.
[crash-2021-08-20_21.47.05-server.txt](https://github.com/JayCeeCreates/earlygame/files/7024750/crash-2021-08-20_21.47.05-server.txt)

**Details:** OS is Linux Mint 19.3. Mods were downloaded from Curseforge. All the configs are default, no data/resource packs, created a new world, single-player.

Thanks! Let me know if there's anything I can do to help :)

**Comment by crysthala** [comment]
Further testing reveals that setting `"enablePlanksAndSticks": true` allows the game to start normally. I think it's EG asking for Indrev's recipes the usual way, not realizing that Indrev's recipes want different "getters" because of the possibility of multiple in/out stacks. Indrev crashes the game in protest, thus destroying my dream of banging pointy rocks together inside my fully-automated multiblock ore processing facility. I'm guessing, anyway. I'm not a real programmer.

**Comment by toruPuchuu** [comment]
I had the same EarlyGame crash: "Unsupported method for Industrial Revolution's recipes". I'm using Windows 10. As above, I was able to work around this by enabling planks and sticks. BTW, machines are not early game, so trying to remove them seems out of scope for EarlyGame...

**Comment by crysthala** [comment]
This was fixed in the Industrial Revolution update. Thanks anyway :)
