### ISSUE TITLE
1.18 and 1.18.1

### ISSUE THREAD

**Issue by theDerxu** [JayCeeCreates/earlygame#36]
Sent you this on Reddit, thought id send it here too so that you see it:  (@JayCeeCreates)

Hey uh just wondering, when dya think you can update the "earlygame" mod, I want to use it on 1.18 but there is no version for it yet. Tried myself and got error code 0 so I would enjoy having it updated to 1.18 and 1.18.1. Ofc thats if you want to, just thought id let you know.

**Comment by theDerxu** [comment]
Is anyone able to respond? It's been a bit. I really want to play it with 1.18, tell me if you can do it perhaps, thanks lol.

**Comment by qb20nh** [comment]
@TheDerpu0ne
Check out @JayCeeCreates 's update
https://github.com/JayCeeCreates/earlygame/pull/37
Download build here
https://drive.google.com/file/d/19ebQyfTyHl9lhybnHm5IEHG9crhIHKPk/view?usp=sharing

**Comment by JayCeeCreates** [comment]
Recently tested the pull request and changed a lot of things for the 1.18.2 release! Stay tuned!
