### ISSUE TITLE
You can't mine stone with stone pickaxe?

### ISSUE THREAD

**Issue by Laifsyn** [JayCeeCreates/earlygame#42]
You can't mine stone with stone pickaxe?(or stone tools) So What's the use of stone tools if so?
There's no information about the changes to stone tools and interactions. What other changes were there?

**Comment by JayCeeCreates** [comment]
This mod disables the functionality of wood and stone tools by default, but you can enable them again if you want by opening:
`.minecraft/config/earlygame.json`

Look for the `crafting` section of the file and set `enableWoodenTools` and/or `enableStoneTools` to true.

You can download Mod Menu if you want more information about the configuration.
