### ISSUE TITLE
1.19.2 boot crash

### ISSUE THREAD

**Issue by SylisMC** [JayCeeCreates/earlygame#49]
You may already be aware of this, or it may be intentional. But the latest version of earlygame has Minecraft 1.19 as a dependency, so it won't boot with 1.19.1 or 2. I would love to bug test for the latest version if that's a concern prior to an official 1.19.2 upload

**Comment by realguyman** [comment]
As a note for the future, you can override the Minecraft dependency requirement for earlygame (or any other mod) with a [`fabric_loader_dependencies.json`](https://fabricmc.net/wiki/tutorial:dependency_overrides) file for experimental purposes.
