### ISSUE TITLE
Incompatibility with Charm (fabric)

### ISSUE THREAD

**Issue by pjlasl** [JayCeeCreates/earlygame#5]
I am using your mod along side [Charm](https://www.curseforge.com/minecraft/mc-mods/charm) and I noticed that I am unable to break the woodcutter item.

I was using the copper axe to break it, so I tried the iron axe, and I am still unable to break it (even by hand).

Without your mod installed, the item breaks as expected...

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

I looked into it, and it appears that the woodcutter has a material of stone, but would be broken using an axe. Now my code required that if a material of the block is stone, it can only be broken using a pickaxe. As of this writing, there doesn't seem to be a method that checks and returns the `breakByTool` of a block.

I'll keep you in touch when I fix it~

**Comment by JayCeeCreates** [comment]
Hi! Just to let you know the mod has been updated to "fix" the incompatibility issue. You can download it on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/earlygame/files/3200431) or through the [Releases](https://github.com/JayCeeCreates/earlygame/releases/tag/1.16.x-1.1.0b) page.

Lemme know if you have further inquiries.

**Comment by pjlasl** [comment]
I downloaded it and I was able to break my woodcutter. Thanks!

**Comment by JayCeeCreates** [comment]
Glad to be of help~
