### ISSUE TITLE
Bits And Chisels incompat

### ISSUE THREAD

**Issue by MissGamerz** [JayCeeCreates/earlygame#7]
the mod bits and chisels adds chisels and bits(A forge mod) functionality to fabric LINK: https://www.curseforge.com/minecraft/mc-mods/bits-and-chisels

your plugin stops all functionality of the chisels in that mod completely due to the breaking of blocks you need some sort of whitelist of tool and make them part of it

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

I've looked into the source code for Bits and Chisels, and it turns out both chisel tools have stone material properties, which was disabled by my mod.

I'll look into the fix.

**Comment by JayCeeCreates** [comment]
Check out the latest release! It should be fixed by now-
