### ISSUE TITLE
No Tree Punching style recipe for flint shards

### ISSUE THREAD

**Issue by Beethoven-n** [JayCeeCreates/earlygame#8]
I really miss this feature from No Tree Punching. You should be able to either craft a knife and a rock together to get one flint shard, or hold one of each in each hand, and right click to take some durability off the knife for a chance at a flint shard.

**Comment by JayCeeCreates** [comment]
Yo, thanks for your input!

If I add this functionality, I'd make it so that when you use your knife on a rock lying on the ground, it will do as you wish. Will that suffice?

**Comment by Beethoven-n** [comment]
that should be good! a standard crafting recipe would also work if that's too much effort

**Comment by JayCeeCreates** [comment]
Well, I'm not planning to put back the modded shapeless recipe stuff again so...

**Comment by JayCeeCreates** [comment]
Latest release is out! It should be implemented by now. Just sneak and use your knife (right-click) on a rock lying around the surface.
